import { once } from "node:events";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { WebSocketServer } from "ws";
import { expect, it } from "vitest";
import Relay, { answerMessages, ratingRequestPart, ratingRequestPartsError,
  RELAY_WEBHOOK_EVENT_TYPES, signWebhookHeaders, type RelayWebhookEvent,
  type RatingRequestPartResponse } from "../src/index.js";

// Real route responses and exact serialized outbox bodies, not invented envelopes.
// The fixture README records generation and what the local socket does not prove.
const fixture = JSON.parse(readFileSync(new URL("../../../test/fixtures/rating-server.json", import.meta.url), "utf8"));
const bodies: string[] = fixture.webhook_bodies;
const events: RelayWebhookEvent[] = bodies.map(body => JSON.parse(body));
const connectionId = "01993d50-b4ce-71e6-8e65-35d325d95ddb";

it("uses rating payloads generated by the pinned Server contract", () => {
  const contract = readFileSync(new URL("../../../contracts/relay-v1-openapi.yaml", import.meta.url));
  // A later contract that leaves every rating schema alone carries the
  // fixture forward by name (source.carried_to) instead of regenerating it.
  expect(createHash("sha256").update(contract).digest("hex"))
    .toBe(fixture.source.carried_to?.contract_sha256 ?? fixture.source.contract_sha256);
  expect(events.map(event => event.event_type)).toEqual(["rating.created", "rating.updated", "rating.deleted"]);
  expect(events[0]!.data).toMatchObject({ stars: 4, review: null });
  expect(events[1]!.data).toMatchObject({ stars: 5, review: "Helped with the test." });
  expect(Object.keys(events[2]!.data)).toEqual(["contact"]);
});

it("sends a bare rating request; the agent response never carries the person's rating", async () => {
  const calls: unknown[] = [];
  const part: RatingRequestPartResponse = { type: "rating_request", value: "Enjoying Echo?", rating: null, reactions: null };
  const client = new Relay({ apiKey: "fixture", fetch: async (_, init) => {
    calls.push(JSON.parse(String(init?.body))); return Response.json(fixture.send_response);
  } });
  const result = await client.chats.messages.send(fixture.send_response.chat_id, { message: { parts: [ratingRequestPart()] } });
  expect(calls).toEqual([{ message: { parts: [{ type: "rating_request" }] } }]);
  expect(result).toEqual(fixture.send_response);
  expect(result.message.parts).toEqual([part]);
  expect(fixture.agent_card_after_rating).toEqual(part);
  expect(fixture.person_card_after_rating.rating).toEqual({ stars: 5, review: "Helped with the test." });
  expect(ratingRequestPartsError([ratingRequestPart()])).toBeUndefined();
  for (const parts of [[ratingRequestPart(), { type: "text", value: "Words" }],
    [{ type: "rating_request", rating: 5 }], [{ type: "rating_request", handle: "other" }],
    [{ type: "rating_request", title: "Rate me" }]]) expect(ratingRequestPartsError(parts)).toBeTypeOf("string");
});

it("text-only bridges send the empty rating fence alone, without inventing a target or words", () => {
  expect(answerMessages('```rating_request\n{}\n```')).toEqual({ messages: [[{ type: "rating_request" }]] });
  for (const text of ['Words\n```rating_request\n{}\n```', '```rating_request\n{"stars":5}\n```',
    '```rating_request\n{}\n```\n```buttons\n["Yes"]\n```']) {
    const result = answerMessages(text); expect(result.error).toBeTruthy();
    expect(result.messages).toEqual([[{ type: "text", value: text }]]);
  }
});

for (const [index, type] of (["rating.created", "rating.updated", "rating.deleted"] as const).entries()) {
  it(`verifies signed ${type} unchanged`, () => {
    expect(RELAY_WEBHOOK_EVENT_TYPES).toContain(type);
    const event = events[index]!; const body = bodies[index]!;
    const secret = `whsec_${Buffer.alloc(32, 12).toString("base64")}`;
    const client = new Relay({ apiKey: "fixture", webhookSecret: secret });
    const headers = signWebhookHeaders(secret, { id: event.event_id, body });
    expect(client.webhooks.unwrap(body, { headers })).toEqual(event);
    expect(() => client.webhooks.unwrap(body + " ", { headers })).toThrow();
  });
  it(`delivers and ACKs ${type} instead of dropping it as unknown`, async () => {
    const event = events[index]!; const server = new WebSocketServer({ port: 0, host: "127.0.0.1" });
    await once(server, "listening"); const address = server.address();
    if (!address || typeof address === "string") throw Error("address missing");
    const controller = new AbortController(); const received: unknown[] = [];
    let subscribed: string[] = [];
    const errors: unknown[] = [];
    let ack!: (value: unknown) => void; const acknowledged = new Promise(resolve => { ack = resolve; });
    server.on("connection", (socket, request) => {
      subscribed = new URL(request.url!, "http://localhost").searchParams.getAll("subscribed_events");
      socket.on("message", raw => { const frame = JSON.parse(String(raw)); if (frame.type === "ack") ack(frame); });
      socket.send(JSON.stringify({ type: "ready", connection_id: connectionId, acked_through: "0", full_sync_required: false,
        full_sync_through: null, heartbeat_interval_ms: 30_000, max_in_flight: 64 }));
      socket.send(JSON.stringify({ type: "event", sequence: "1", event }));
    });
    const client = new Relay({ apiKey: "fixture", baseURL: `http://127.0.0.1:${address.port}` });
    const running = client.websocket.run({ signal: controller.signal, onFullSync: async () => {},
      onError: error => { errors.push(error); },
      onEvent: async value => { received.push(value); } });
    try {
      expect(await acknowledged).toEqual({ type: "ack", through_sequence: "1" });
      expect(received).toEqual([event]);
      expect(subscribed).toContain(type);
      expect(errors).toEqual([]);
    }
    finally { controller.abort(); await running; for (const socket of server.clients) socket.terminate(); await new Promise<void>(resolve => server.close(() => resolve())); }
  });
}
