// Derives what a production release publishes from the tree as staging wrote
// it. Nothing is published by hand and no version-bump PR exists (owner
// ruling, 2026-09-07): main is staging's exact tree, every manifest there says
// `X.Y.Z-staging.N`, and the release job on main strips the prerelease to
// `X.Y.Z`, pins the Relay packages to each other at those plain versions,
// skips what npm already has, and publishes the rest as `latest`.
//
// This file is the pure part: derivation, order, plan, and the manifest
// rewrite. scripts/release-run.mjs drives npm, git, and GitHub around it.
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { releaseKeys, releasePackages } from "./release-packages.mjs";

// A plain release version, optionally carrying the staging prerelease the
// estate uses everywhere. Nothing else derives: `0.3.0-rc.1` or `1.2` fail
// closed rather than guess.
const VERSION_SHAPE = /^(\d+\.\d+\.\d+)(?:-staging\.\d+)?$/u;

export function deriveVersion(version) {
  const match = VERSION_SHAPE.exec(String(version));
  if (!match) {
    throw new Error(
      `cannot derive a release version from ${JSON.stringify(version)}: `
        + "expected X.Y.Z or X.Y.Z-staging.N",
    );
  }
  return match[1];
}

export function readManifests(root) {
  const manifests = {};
  for (const key of releaseKeys) {
    manifests[key] = JSON.parse(
      readFileSync(join(root, releasePackages[key].directory, "package.json"), "utf8"),
    );
  }
  return manifests;
}

const DEPENDENCY_FIELDS = [
  "dependencies",
  "peerDependencies",
  "optionalDependencies",
  "devDependencies",
];

/** The Relay packages this manifest depends on, by catalog key. */
export function internalDependencies(manifest, manifests) {
  const byName = new Map(
    Object.entries(manifests).map(([key, value]) => [value.name, key]),
  );
  const found = [];
  for (const field of DEPENDENCY_FIELDS) {
    for (const name of Object.keys(manifest[field] ?? {})) {
      const key = byName.get(name);
      if (key) found.push({ field, name, key });
    }
  }
  return found;
}

/**
 * The catalog order is the publish order. A dependent's validation installs
 * its Relay dependencies from npm, so every dependency must come earlier.
 */
export function releaseOrder(manifests, order = releaseKeys) {
  order = order.filter((key) => key in manifests);
  for (const [position, key] of order.entries()) {
    for (const dependency of internalDependencies(manifests[key], manifests)) {
      const dependencyPosition = order.indexOf(dependency.key);
      assert.ok(
        dependencyPosition !== -1 && dependencyPosition < position,
        `${key} depends on ${dependency.key}, which must release before it`,
      );
    }
  }
  return order;
}

/**
 * One row per package: the version in the tree, the derived release version,
 * and whether npm already has it. `isPublished(name, version)` is injected so
 * the plan is testable and so a dry run can be told to assume a publish.
 */
export function releasePlan(manifests, isPublished) {
  return releaseOrder(manifests).map((key) => {
    const manifest = manifests[key];
    assert.equal(manifest.name, releasePackages[key].workspace);
    const version = deriveVersion(manifest.version);
    const published = Boolean(isPublished(manifest.name, version));
    return {
      key,
      name: manifest.name,
      directory: releasePackages[key].directory,
      tag: `${releasePackages[key].tagPrefix}${version}`,
      current: manifest.version,
      version,
      published,
      action: published ? "skip" : "publish",
    };
  });
}

const readJson = (path) => JSON.parse(readFileSync(path, "utf8"));
const writeJson = (path, value) =>
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);

/**
 * Rewrites one package for release: its own version, every Relay dependency
 * pinned to the derived plain version, and the package's contract lock where
 * it carries the SDK version (and the SDK's registry integrity once known).
 * Files that embed the version are regenerated by each package's own build,
 * never edited here. Returns the paths written.
 */
export function rewritePackage(root, key, plan, { sdkIntegrity = null } = {}) {
  const row = plan.find((entry) => entry.key === key);
  assert.ok(row, `${key} is not in the release plan`);
  const versions = new Map(plan.map((entry) => [entry.name, entry.version]));
  const manifestPath = join(root, row.directory, "package.json");
  const manifest = readJson(manifestPath);
  manifest.version = row.version;
  for (const field of DEPENDENCY_FIELDS) {
    for (const name of Object.keys(manifest[field] ?? {})) {
      if (versions.has(name)) manifest[field][name] = versions.get(name);
    }
  }
  writeJson(manifestPath, manifest);
  const written = [manifestPath];

  const lockPaths = {
    openclaw: ["contracts/relay-v1.lock.json"],
    "claude-code": [
      "contracts/relay-v1.lock.json",
      "plugin/contracts/relay-v1.lock.json",
    ],
  }[key] ?? [];
  for (const relative of lockPaths) {
    const path = join(root, row.directory, relative);
    const lock = readJson(path);
    lock.relaySdk.version = versions.get(lock.relaySdk.package);
    if (sdkIntegrity) lock.relaySdk.integrity = sdkIntegrity;
    writeJson(path, lock);
    written.push(path);
  }
  if (key === "claude-code") {
    for (const relative of [
      ".claude-plugin/plugin.json",
      "plugin/.claude-plugin/plugin.json",
    ]) {
      const path = join(root, row.directory, relative);
      const plugin = readJson(path);
      plugin.version = row.version;
      writeJson(path, plugin);
      written.push(path);
    }
    const marketplacePath = join(root, row.directory, ".claude-plugin/marketplace.json");
    const marketplace = readJson(marketplacePath);
    marketplace.plugins[0].version = row.version;
    writeJson(marketplacePath, marketplace);
    written.push(marketplacePath);
  }
  return written;
}
