// Derives what a production release publishes from the tree as staging wrote
// it. Nothing is published by hand and no version-bump PR exists (owner
// ruling, 2026-09-07): main is staging's exact tree, every manifest there says
// `X.Y.Z-staging.N`, and the release job on main strips the prerelease to
// `X.Y.Z`, pins the Relay packages to each other at those plain versions,
// skips what npm already has, and publishes the rest as `latest`.
//
// This file is the pure part: derivation, order, plan, and the manifest
// rewrite. scripts/release-run.mjs drives npm, git, and GitHub around it.
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { releaseKeys, releasePackages } from "./release-packages.mjs";

// A plain release version, optionally carrying the staging prerelease the
// estate uses everywhere. Nothing else derives: `0.3.0-rc.1` or `1.2` fail
// closed rather than guess.
const VERSION_SHAPE = /^(\d+\.\d+\.\d+)(?:-staging\.\d+)?$/u;

export function deriveVersion(version) {
  const match = VERSION_SHAPE.exec(String(version));
  if (!match) {
    throw new Error(
      `cannot derive a release version from ${JSON.stringify(version)}: `
        + "expected X.Y.Z or X.Y.Z-staging.N",
    );
  }
  return match[1];
}

export function readManifests(root) {
  const manifests = {};
  for (const key of releaseKeys) {
    manifests[key] = JSON.parse(
      readFileSync(join(root, releasePackages[key].directory, "package.json"), "utf8"),
    );
  }
  return manifests;
}

const DEPENDENCY_FIELDS = [
  "dependencies",
  "peerDependencies",
  "optionalDependencies",
  "devDependencies",
];

/** The Relay packages this manifest depends on, by catalog key. */
export function internalDependencies(manifest, manifests) {
  const byName = new Map(
    Object.entries(manifests).map(([key, value]) => [value.name, key]),
  );
  const found = [];
  for (const field of DEPENDENCY_FIELDS) {
    for (const name of Object.keys(manifest[field] ?? {})) {
      const key = byName.get(name);
      if (key) found.push({ field, name, key });
    }
  }
  return found;
}

/**
 * The catalog order is the publish order. A dependent's validation installs
 * its Relay dependencies from npm, so every dependency must come earlier.
 */
export function releaseOrder(manifests, order = releaseKeys) {
  order = order.filter((key) => key in manifests);
  for (const [position, key] of order.entries()) {
    for (const dependency of internalDependencies(manifests[key], manifests)) {
      const dependencyPosition = order.indexOf(dependency.key);
      assert.ok(
        dependencyPosition !== -1 && dependencyPosition < position,
        `${key} depends on ${dependency.key}, which must release before it`,
      );
    }
  }
  return order;
}

/**
 * One row per package: the version in the tree, the derived release version,
 * and whether npm already has it. `isPublished(name, version)` is injected so
 * the plan is testable and so a dry run can be told to assume a publish.
 */
export function releasePlan(manifests, isPublished) {
  return releaseOrder(manifests).map((key) => {
    const manifest = manifests[key];
    assert.equal(manifest.name, releasePackages[key].workspace);
    const version = deriveVersion(manifest.version);
    const published = Boolean(isPublished(manifest.name, version));
    return {
      key,
      name: manifest.name,
      directory: releasePackages[key].directory,
      tag: `${releasePackages[key].tagPrefix}${version}`,
      current: manifest.version,
      version,
      published,
      action: published ? "skip" : "publish",
    };
  });
}

const readJson = (path) => JSON.parse(readFileSync(path, "utf8"));
const writeJson = (path, value) =>
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);

/**
 * Rewrites one package for release: its own version, every Relay dependency
 * pinned to the derived plain version, and the package's contract lock where
 * it carries the SDK version (and the SDK's registry integrity once known).
 * Files that embed the version are regenerated by each package's own build,
 * never edited here. Returns the paths written.
 */
export function rewritePackage(root, key, plan, { sdkIntegrity = null } = {}) {
  const row = plan.find((entry) => entry.key === key);
  assert.ok(row, `${key} is not in the release plan`);
  const versions = new Map(plan.map((entry) => [entry.name, entry.version]));
  const manifestPath = join(root, row.directory, "package.json");
  const manifest = readJson(manifestPath);
  manifest.version = row.version;
  for (const field of DEPENDENCY_FIELDS) {
    for (const name of Object.keys(manifest[field] ?? {})) {
      if (versions.has(name)) manifest[field][name] = versions.get(name);
    }
  }
  writeJson(manifestPath, manifest);
  const written = [manifestPath];

  const lockPaths = {
    openclaw: ["contracts/relay-v1.lock.json"],
    "claude-code": [
      "contracts/relay-v1.lock.json",
      "plugin/contracts/relay-v1.lock.json",
    ],
  }[key] ?? [];
  for (const relative of lockPaths) {
    const path = join(root, row.directory, relative);
    const lock = readJson(path);
    lock.relaySdk.version = versions.get(lock.relaySdk.package);
    if (sdkIntegrity) lock.relaySdk.integrity = sdkIntegrity;
    writeJson(path, lock);
    written.push(path);
  }
  if (key === "claude-code") {
    for (const relative of [
      ".claude-plugin/plugin.json",
      "plugin/.claude-plugin/plugin.json",
    ]) {
      const path = join(root, row.directory, relative);
      const plugin = readJson(path);
      plugin.version = row.version;
      writeJson(path, plugin);
      written.push(path);
    }
    const marketplacePath = join(root, row.directory, ".claude-plugin/marketplace.json");
    const marketplace = readJson(marketplacePath);
    marketplace.plugins[0].version = row.version;
    writeJson(marketplacePath, marketplace);
    written.push(marketplacePath);
  }
  return written;
}

/**
 * Every file under `directory` (node_modules excluded) whose bytes still
 * carry `version`, relative to `directory`. The release job runs this over the
 * unpacked tarball with the pre-rewrite staging version: a file it lists is a
 * place the version lived that neither the rewrite nor the package's own build
 * derived. The first release on main published nothing for claude-code because
 * runtime/server.mjs still embedded `0.3.0-staging.6` (2026-09-07); this is
 * the closed door for every such file, generated or checked in.
 */
export function filesCarryingVersion(directory, version) {
  const needle = Buffer.from(version);
  const found = [];
  const walk = (current, relative) => {
    for (const name of readdirSync(current)) {
      if (name === "node_modules") continue;
      const path = join(current, name);
      const child = relative ? `${relative}/${name}` : name;
      if (statSync(path).isDirectory()) walk(path, child);
      else if (readFileSync(path).includes(needle)) found.push(child);
    }
  };
  walk(directory, "");
  return found.sort();
}

/** Derive even skipped workspaces before resolving dependents against them. */
export function rewriteReleaseWorkspace(root, plan, options = {}) {
  return plan.flatMap((row) => rewritePackage(root, row.key, plan, options));
}

// A Relay pin in a cookbook that names a staging build: an exact
// `X.Y.Z-staging.N`, or a `^`/`~` range whose lower bound is one.
const COOKBOOK_PRERELEASE_PIN = /^([\^~]?)(\d+\.\d+\.\d+-staging\.\d+)$/u;
// What a copied cookbook never carries (validate-cookbook-standalone.mjs).
const COOKBOOK_SKIP = new Set([".artifacts", ".dev.vars", ".git", ".wrangler", "coverage", "dist", "node_modules"]);

function cookbookFiles(directory) {
  const found = [];
  const walk = (current) => {
    for (const name of readdirSync(current)) {
      if (COOKBOOK_SKIP.has(name)) continue;
      const path = join(current, name);
      if (statSync(path).isDirectory()) walk(path);
      else found.push(path);
    }
  };
  walk(directory);
  return found.sort();
}

/** Every cookbook folder under `root` that has a package.json. */
export function cookbookDirectories(root) {
  const cookbookRoot = join(root, "cookbook");
  return readdirSync(cookbookRoot)
    .map((name) => join(cookbookRoot, name))
    .filter((path) => statSync(path).isDirectory() && existsSync(join(path, "package.json")))
    .sort();
}

/** The Relay pins in a cookbook manifest that still name a staging build. */
export function cookbookPrereleasePins(manifest, plan) {
  const names = new Set(plan.map((row) => row.name));
  const found = [];
  for (const field of DEPENDENCY_FIELDS) {
    for (const [name, range] of Object.entries(manifest[field] ?? {})) {
      if (names.has(name) && /-staging\./u.test(range)) found.push({ field, name, range });
    }
  }
  return found;
}

/**
 * Rewrites one cookbook's Relay prerelease pins to the versions the release
 * publishes, the same derivation rewritePackage applies to the packages. The
 * cookbook-standalone check on main installs a copied folder from npm's
 * `latest` and rejects any prerelease (validate-cookbook-standalone.mjs), so
 * a staging pin such as the Think starter's `0.3.6-staging.46` has to become
 * the plain `0.3.6` the release publishes.
 *
 * An exact pin becomes the plan's version; every other file in the folder
 * that carries the pinned staging version (its package-lock.json entry and
 * tarball URL, a contract test, the README) follows, and a lockfile's
 * integrity for that package becomes `integrityByName.get(name)`, the
 * integrity of the tarball the release publishes. A `^`/`~` range keeps its
 * operator and loses only the prerelease. Fails closed when a staging version
 * survives anywhere in the folder. Returns the paths written.
 */
export function rewriteCookbook(directory, plan, { integrityByName = new Map() } = {}) {
  const manifestPath = join(directory, "package.json");
  const manifest = readJson(manifestPath);
  const pins = cookbookPrereleasePins(manifest, plan);
  if (pins.length === 0) return [];
  const lockPath = join(directory, "package-lock.json");
  const lock = existsSync(lockPath) ? readJson(lockPath) : null;
  const replacements = [];
  for (const { field, name, range } of pins) {
    const match = COOKBOOK_PRERELEASE_PIN.exec(range);
    assert.ok(match, `${directory} pins ${name}@${range}; only X.Y.Z-staging.N, ^X.Y.Z-staging.N or ~X.Y.Z-staging.N derive`);
    const [, operator, staging] = match;
    const row = plan.find((entry) => entry.name === name);
    if (operator) {
      assert.equal(lock?.packages?.[`node_modules/${name}`], undefined,
        `${directory} locks ${name} under the range ${range}; pin it exactly so the release can rewrite the lock`);
      manifest[field][name] = `${operator}${deriveVersion(staging)}`;
      continue;
    }
    manifest[field][name] = row.version;
    replacements.push([staging, row.version]);
    const locked = lock?.packages?.[`node_modules/${name}`];
    if (locked?.integrity) {
      assert.equal(locked.version, staging, `${directory} locks ${name}@${locked.version} but pins ${staging}`);
      const integrity = integrityByName.get(name);
      assert.ok(integrity, `${directory} locks ${name}; the release has no integrity for ${name}@${row.version}`);
      replacements.push([locked.integrity, integrity]);
    }
  }
  const staleVersions = pins.map(({ range }) => COOKBOOK_PRERELEASE_PIN.exec(range)[2]);
  const counts = new Map(staleVersions.map((version) => [version, 0]));
  for (const version of staleVersions) counts.set(version, counts.get(version) + 1);
  for (const [version, count] of counts) {
    assert.equal(count, 1, `${directory} pins two Relay packages at ${version}; the rewrite cannot tell them apart`);
  }
  writeJson(manifestPath, manifest);
  const written = new Set([manifestPath]);
  for (const path of cookbookFiles(directory)) {
    const before = readFileSync(path);
    if (before.includes(0)) continue;
    let text = before.toString("utf8");
    for (const [from, to] of replacements) text = text.split(from).join(to);
    if (path === lockPath && lock) {
      // The lock's root entry repeats the manifest's ranges; keep them equal.
      const rewritten = JSON.parse(text);
      for (const field of DEPENDENCY_FIELDS) {
        for (const [name, range] of Object.entries(manifest[field] ?? {})) {
          if (rewritten.packages?.[""]?.[field]?.[name] !== undefined) rewritten.packages[""][field][name] = range;
        }
      }
      text = `${JSON.stringify(rewritten, null, 2)}\n`;
    }
    if (text !== before.toString("utf8")) {
      writeFileSync(path, text);
      written.add(path);
    }
  }
  if (lock) {
    // Any Relay package the lockfile still resolves to a staging build, at
    // any depth, is one the release did not derive.
    const names = new Set(plan.map((row) => row.name));
    for (const [key, entry] of Object.entries(readJson(lockPath).packages ?? {})) {
      const name = key.split("node_modules/").pop();
      assert.ok(!(names.has(name) && /-staging\./u.test(entry.version ?? "")),
        `${lockPath} still resolves ${key} to ${entry.version} after the release rewrite`);
    }
  }
  for (const path of cookbookFiles(directory)) {
    const bytes = readFileSync(path);
    for (const version of staleVersions) {
      assert.ok(!bytes.includes(Buffer.from(version)), `${path} still carries ${version} after the release rewrite`);
    }
  }
  return [...written].sort();
}

/** rewriteCookbook over every cookbook folder. Returns the paths written. */
export function rewriteCookbooks(root, plan, options = {}) {
  return cookbookDirectories(root).flatMap((directory) => rewriteCookbook(directory, plan, options));
}
